apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: monitoring
  name: prometheus-storage
  labels:
    app: prometheus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: prometheus

